#docker-compose.yml

version: "3.3"

services:
  laracom-user-service:
    depends_on:
      - laracom-user-db
    build:
      ./user-service
    ports:
      - 9092:9091
    environment:
      MICRO_SERVER_ADDRESS: ":9091"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "laracom-user-db:3306"
      DB_NAME: "laracom_user"
      DB_USER: "root"
      DB_PASSWORD: "root"
  laracom-user-db:
    image: mysql:5.7
    container_name: laracom-user-db
    ports:
      - 3309:3306
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_DATABASE: "laracom_user"
      MYSQL_ROOT_PASSWORD: "root"
  laracom-user-cli:
    build: ./user-cli
    environment:
      MICRO_REGISTRY: "mdns"
volumes:
  db_data: {}